### ISSUE TITLE
How to escape special characters in datasource name?

### ISSUE THREAD

**Issue by theduderog** [facetjs/facet-cli#1]
$facet -h localhost  -i P1D -q 'select count() from `svc-perf`'
    Could not parse query as SQL: SQL parse error Expected "`" but "-" found. on `select count() from `svc-perf``

**Comment by theduderog** [comment]
BTW, adding -d='svc-perf' doesn't work

**Comment by vogievetsky** [comment]
Ok. good point. I feel silly. Will fix in next version.

**Comment by vogievetsky** [comment]
Just to be a little clearer: the facet-cli translates SQL to facet and then evaluates it.
facet currently only allows variables that follow the same rules as standard Java like languages.
I basically waited for someone to have an issue with this before implementing more permissive variable names (such as `svc-perf`).

I will make the necessary changes early next week.

**Comment by theduderog** [comment]
Thanks for the explanation and fix.

BTW, is there a way to see the intermediate facet query?  I saw the -v option which prints the Druid query.

**Comment by vogievetsky** [comment]
There is no way right now to see the intermediate facet query but that is a
great idea. I will definitely add that. Just need to decide if it should be
part of verbose mode (-v) or have its own flag. Decisions... decisions...
designing CLIs is hard.

**Comment by theduderog** [comment]
This is a really great project. I love the idea of a facet query spec with drivers for multiple backends.   Thanks for creating and sharing it.

**Comment by vogievetsky** [comment]
Thank you @theduderog I appreciate it.

That is precisely the idea: to have an intermediate language (facet spec) that can express whatever data operation you desire. Then a set of drivers can convert that spec to any supported database and also act like polyfills for any missing features that the database does not provide. This is especially useful for Druid as it needs quite a bit of polyfilling.

The overall goal is to make it easier for people to build web based data applications. That is why facet is written in a language that compiles to JavaScript (TypeScript).

I have added a line of code:
https://github.com/facetjs/facet-cli/commit/35744f700e41f9d332d93ba0064f29450291cf4f#diff-cd02b9e0b731a6a1dedefed142f4419bR192
that will spit out the JSON serialized version of the intermediate facet expression. It is not super pretty to look at but it is easy for a machine to work with it. I will also add an ability to the CLI to spit out the human friendly version of the parsed facet expression at some point soon.

Now, I'll dive into making the variable names less restrictive.

I look forward to seeing your talk (and meeting you in person) at tomorrow's Samza meetup

**Comment by vogievetsky** [comment]
Fixed it. https://github.com/facetjs/facet-cli/commit/150bd801fdecae6ff97e0477375f3c272f3d0e68
Please try 

```
$facet -h localhost  -i P1D -q 'select count() from `svc-perf`'
```
it and let me know if it works. (run `npm install -g facet-cli` again to get the latest version).
Going to close this issue, please reopen it if the query does not work for you.

Just in time for your talk. *closes laptop*

**Comment by theduderog** [comment]
It works!  Thank you!

    $ facet -v -h localhost -i P1D -q 'select sum(totalCalls) as calls from `svc-perf` group by workgroup order by calls asc'
